           image:
            db:
            repository: devopseasylearning2021/s4-db
            tag: "v8.0.0"
         ui:
            repository: devopseasylearning2021/s4-ui
            tag: "v6.0.0"
         auth:
            repository: devopseasylearning2021/s4-auth
            tag: "v3.0.0"
         weather:
            repository: devopseasylearning2021/s4-weather
           tag: "v7.0.0"
